name: Build luci-app-adguardhome APK for OpenWrt 25.12
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev wget tar zstd

      - name: Download & Extract OpenWrt 25.12.0 SDK x86_64 (USTC mirror)
        run: |
          wget --tries=10 https://mirrors.ustc.edu.cn/openwrt/releases/25.12.0/targets/x86/64/openwrt-sdk-25.12.0-x86-64_gcc-14.3.0_musl.Linux-x86_64.tar.zst
          tar -I zstd -xf openwrt-sdk*.tar.zst
          ls -la
          SDK_DIR=$(find . -maxdepth 1 -type d -name "openwrt-sdk-*")
          mv "$SDK_DIR" openwrt-sdk

      - name: Checkout source
        uses: actions/checkout@v4
        with:
          path: src

      - name: Copy plugin into SDK package & list files
        run: |
          cp -r src/luci-app-adguardhome openwrt-sdk/package/
          echo "==== package dir files ===="
          ls -la openwrt-sdk/package/luci-app-adguardhome/

      - name: Build package
        run: |
          cd openwrt-sdk
          export TERM=dumb
          ./scripts/feeds update -a
          ./scripts/feeds install luci-compat
          make defconfig
          echo "==== try to clean ===="
          make package/luci-app-adguardhome/clean
          echo "==== try compile ===="
          make -j1 V=sc package/luci-app-adguardhome/compile
          echo "==== try install ===="
          make -j1 V=sc package/luci-app-adguardhome/install
          echo "==== try package ===="
          make -j1 V=sc package/luci-app-adguardhome/package
          ls -la bin/packages/x86_64/luci/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-adguardhome-apk
          path: openwrt-sdk/bin/packages/x86_64/luci/luci-app-adguardhome*.apk
